# Site settings
title: Saad Najafi
description: CodeChain Validator
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Saad Najafi
user_description: Seoul National University Master's Student, CodeChain Validator, CodeChain Core Developer, Blockchain Enthusiast, Graph devoteer.
user_title: CodeChain Core Developer
email: najafi@codechain.io
twitter_username: saadnajafi
github_username: MSNTCS
gplus_username:

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
